### ISSUE TITLE
File encoding issue

### ISSUE THREAD

**Issue by RamonWill** [sqlalchemyorg/zimports#14]
Operating System: Window 10
pre-commit version: 2.5.1 

Earlier today i made a Pull Request to fix a few typos i found inside 5 SQLAlchemy files. I have pre-commit installed so that black formatting, flake8 and zimports checks are made before my commit.

However, the zimports check raised the below error when i tried to make a commit with the file SQLAlchemy file [test_quote.py](https://github.com/sqlalchemy/sqlalchemy/blob/master/test/sql/test_quote.py):

```
zimports.................................................................Failed
- hook id: zimports
- exit code: 1
Traceback (most recent call last):
  File "c:\users\owner\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\owner\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Owner\.cache\pre-commit\repov34h3x3z\py_env-python3.7\Scripts\zimports.EXE\__main__.py", line 7, in <module>
  File "c:\users\owner\.cache\pre-commit\repov34h3x3z\py_env-python3.7\lib\site-packages\zimports.py", line 698, in main
    _run_file(options, filename)
  File "c:\users\owner\.cache\pre-commit\repov34h3x3z\py_env-python3.7\lib\site-packages\zimports.py", line 561, in _run_file
    source_lines = [line.rstrip() for line in file_]
  File "c:\users\owner\.cache\pre-commit\repov34h3x3z\py_env-python3.7\lib\site-packages\zimports.py", line 561, in <listcomp>
    source_lines = [line.rstrip() for line in file_]
  File "c:\users\owner\appdata\local\programs\python\python37\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 1024: character maps to <undefined>
```

After some investigating i found out that because i am on a windows PC and no encoding is specified in zimports.py file the encoding defaults to the systems locale, CP-1252. CP-1252 doesn't contain byte 0x90 thus raising the error.

The workaround i used to resolve this was to make the following edit to line 560 in the zimports.py file (inside the pre-commit cache folder that gets generated):

```diff
##\.cache\pre-commit\repov34h3x3z\py_env-python3.7\lib\site-packages\zimports.py"

def _lines_with_newlines(lines):
    for line in lines:
        yield line + "\n"


def _run_file(options, filename):
-    with open(filename) as file_:
+    with open(filename, encoding="utf8") as file_:

```

So my question is should any changes be made to specify the file encoding explicitly rather than using the default as it currently is? If yes can i make the PR?

I can see that the python community might be moving towards using utf8 as the default encoding [ in the future](https://www.python.org/dev/peps/pep-0597/#omitting-encoding-is-common-mistake)

Thanks,

Ramon

**Comment by zzzeek** [comment]
Python source encoding for python 3 is utf-8 so that should use utf-8, sure.

**Comment by zzzeek** [comment]
https://www.python.org/dev/peps/pep-3120/

**Comment by zzzeek** [comment]
see also #8
